database:
  host: "localhost"
  port: 5432
  username: ""
  password: ""
  database_name: ""
  require_ssl: false
sheets:
  credential_path: credentials/exporter.json
  token_cache_path: credentials/token-cache.json
  spreadsheet_id: ""
