application:
  host: 0.0.0.0
  base_url: "http://localhost:8000"
  port: 8000
  lightstep_access_token: ""
  jwt_secret: ""
database:
  require_ssl: false
  host: "localhost"
  port: 5432
  username: ""
  password: ""
  database_name: ""
bigcommerce:
  api_base_url: https://api.bigcommerce.com
  login_base_url: https://login.bigcommerce.com
  timeout: 10000
  client_secret: ""
  client_id: ""
  install_redirect_uri: http://localhost:8000/bigcommerce/install
liq_pay:
  public_key: "public_key_value"
  private_key: "private_key_value"
